SAMPLE_CASES = [
    {"customer_id": "C001", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C001", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C001", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C001", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C002", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C002", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C002", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C002", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C003", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C003", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C003", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C003", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C003", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C004", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C004", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C005", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C005", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C005", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C005", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C005", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C006", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C006", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C006", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C007", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C007", "text": "Customer payment method failed 3 times consecutively before succeeding."},
    {"customer_id": "C008", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C008", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C008", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C008", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C008", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C009", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C009", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C009", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C009", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C009", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C010", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C010", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C010", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C010", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C011", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C011", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C011", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C011", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C011", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C012", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C012", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C012", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C012", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C013", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C013", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C014", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C014", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C014", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C014", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C015", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C015", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C015", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C016", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C016", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C016", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C017", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C017", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C017", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C018", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C019", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C020", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C020", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C020", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C020", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C021", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C021", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C021", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C021", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C021", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C022", "text": "Customer cancelled ride 2 minutes before pickup."},
    {"customer_id": "C022", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C022", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C023", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C023", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C023", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C023", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C024", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C025", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C025", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C025", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C025", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C026", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C027", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C027", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C028", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C028", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C029", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C029", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C030", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C030", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C030", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C030", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C031", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C032", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C032", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C033", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C034", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C034", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C034", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C034", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C034", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C035", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C035", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C035", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C035", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C036", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C037", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C037", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C038", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C038", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C038", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C038", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C038", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C039", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C039", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C039", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C039", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C040", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C041", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C042", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C042", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C042", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C042", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C043", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C043", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C043", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C044", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C044", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C045", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C045", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C045", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C045", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C046", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C046", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C047", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C047", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C048", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C048", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C048", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C049", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C049", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C050", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C051", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C051", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C051", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C051", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C051", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C052", "text": "Customer reported a missing item in their food delivery."},
    {"customer_id": "C052", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C052", "text": "Customer reported a missing item in their food delivery."},
    {"customer_id": "C052", "text": "Customer left a 1-star rating citing rude behavior from driver."},
    {"customer_id": "C053", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C054", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C054", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C055", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C055", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C055", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C056", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C057", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C058", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C058", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C058", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C058", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C059", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C059", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C059", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C059", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C059", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C060", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C060", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C060", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C060", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C061", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C061", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C061", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C061", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C062", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C062", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C063", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C063", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C064", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C064", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C064", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C064", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C064", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C065", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C065", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C065", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C065", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C065", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C066", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C066", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C066", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C067", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C067", "text": "Customer repeatedly cancels after driver is assigned."},
    {"customer_id": "C067", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C068", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C069", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C069", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C069", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C070", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C070", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C070", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C070", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C070", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C071", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C071", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C071", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C071", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C072", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C072", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C073", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C073", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C073", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C073", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C073", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C074", "text": "Customer payment method failed 3 times consecutively before succeeding."},
    {"customer_id": "C075", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C075", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C075", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C075", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C076", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C076", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C076", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C076", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C076", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C077", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C077", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C077", "text": "Customer left a 1-star rating citing rude behavior from driver."},
    {"customer_id": "C077", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C077", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C078", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C079", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C079", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C079", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C079", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C080", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C080", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C080", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C080", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C080", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C081", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C081", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C082", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C083", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C084", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C084", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C084", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C084", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C085", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C086", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C086", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C086", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C086", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C086", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C087", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C087", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C087", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C087", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C088", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C088", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C088", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C088", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C089", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C089", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C089", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C089", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C089", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C090", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C090", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C090", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C090", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C091", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C091", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C091", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C091", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C092", "text": "Customer filed complaint about food quality, requested full refund."},
    {"customer_id": "C092", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C093", "text": "Customer reported a missing item in their food delivery."},
    {"customer_id": "C094", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C095", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C095", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C095", "text": "Customer account flagged for unusual login locations."},
    {"customer_id": "C095", "text": "Customer disputed multiple charges in one week."},
    {"customer_id": "C096", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C096", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C096", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C096", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C096", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C097", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C097", "text": "Customer disputed a charge claiming they were never picked up."},
    {"customer_id": "C097", "text": "Customer requested a chargeback directly through their bank."},
    {"customer_id": "C097", "text": "Customer used promo code fraudulently across multiple accounts."},
    {"customer_id": "C097", "text": "System detected possible GPS spoofing during the ride."},
    {"customer_id": "C098", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C098", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C098", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C098", "text": "Customer completed 50+ rides with 5-star ratings."},
    {"customer_id": "C098", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C099", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C099", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C099", "text": "Customer tipped the driver 20% and left a positive review."},
    {"customer_id": "C100", "text": "Customer has clean history, no complaints in past 6 months."},
    {"customer_id": "C100", "text": "Customer cancelled last minute due to a genuine emergency."},
    {"customer_id": "C100", "text": "Customer tipped the driver 20% and left a positive review."},
]
